export const actionTypes = {
  // request all charachters
  GET_CHARACTERS_REQUEST: 'GET_CHARACTERS_REQUEST',
  GET_CHARACTERS_SUCCESS: 'GET_CHARACTERS_SUCCESS',
  GET_CHARACTERS_FAILURE: 'GET_CHARACTERS_FAILURE',

  // request one charachter
  GET_CHARACTER_REQUEST: 'GET_CHARACTER_REQUEST',
  GET_CHARACTER_SUCCESS: 'GET_CHARACTER_SUCCESS',
  GET_CHARACTER_FAILURE: 'GET_CHARACTER_FAILURE',

  // request one charachter extended detail
  GET_CHARACTER_EXTENDED_DETAIL_REQUEST: 'GET_CHARACTER_EXTENDED_DETAIL_REQUEST',
  GET_CHARACTER_EXTENDED_DETAIL_SUCCESS: 'GET_CHARACTER_EXTENDED_DETAIL_SUCCESS',
  GET_CHARACTER_EXTENDED_DETAIL_FAILURE: 'GET_CHARACTER_EXTENDED_DETAIL_FAILURE',
};
